# Generated by Django 3.1.4 on 2020-12-27 19:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('website', models.URLField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('status', models.BooleanField()),
                ('photo_version', models.BooleanField()),
                ('ready_to_link', models.BooleanField()),
                ('ordernum', models.IntegerField()),
                ('bad_standing', models.BooleanField()),
                ('zip', models.CharField(blank=True, max_length=15)),
                ('country_short_code', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('lat', models.TextField(blank=True)),
                ('lon', models.TextField(blank=True)),
                ('aid', models.IntegerField()),
                ('org_type', models.CharField(blank=True, max_length=255)),
                ('effective_date', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('show_on_map', models.BooleanField()),
                ('kids', models.BooleanField()),
                ('name_search', models.CharField(blank=True, max_length=255)),
                ('state_code', models.CharField(blank=True, max_length=15)),
                ('full_state', models.CharField(blank=True, max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gyms.city')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gyms.region')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gyms.country'),
        ),
    ]
